global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yml

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.18.0.8:8080']

  - job_name: 'meta-exporter'
    static_configs:
      - targets: ['meta-exporter:8000']
