server:
    host: ENC[AES256_GCM,data:TiSKwpg0dQ==,iv:kizbHlh80i0MuuX5LhCg169EgRGCPd7A+HdkAg0NJ04=,tag:WmMWixzAmDBMsmAzsOtWXw==,type:str]
    port: ENC[AES256_GCM,data:jCGCtA==,iv:sMbZPKo+DS1NpCFhfMC8r19MWfzEWPH/+BLUpKhWSQ4=,tag:MXt1t4GyatCv7fO3A0fUrA==,type:int]
default_redirection_url: ENC[AES256_GCM,data:UTSxgvSaf4F42Pxfnhpi0jPfIq5eZh0VYfNjdo5fLw==,iv:ZmSOYszmWEYQIu+9iJNzLDfTWL+rwrgEbT5r+fs0OjM=,tag:miauuP4NK1+enY5D1XBP/A==,type:str]
log:
    level: ENC[AES256_GCM,data:AulAUQ==,iv:QGOLfkcBGKIfYd1VM3rLpvAsGO4VaK9CBUEM1M25Vkg=,tag:thGIexaMhWOoGjeVsn7j1g==,type:str]
jwt_secret: ENC[AES256_GCM,data:oMk8dMef9mqtLoZttr9h0lG1w/gSfV8ECpkehUQICidDu/Q5FpvoyYs=,iv:oH3GxwX/2Z1KtJZ8v9Bj2IXyujBb32f0kEySQikojIg=,tag:iqFLDz6V2vDy/+qypGrlRw==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:0tJPzOqe5bWae0EBfA7Wj5SkWU01f7CcYpjpIg==,iv:YgZiwSmd7IcEd8HpWwhunI3Rx2EiU8jywzh1/mszASk=,tag:Gknde5AmPNRftg1OywGoxA==,type:str]
    local:
        path: ENC[AES256_GCM,data:pBrWl67hEfPq/rdMDqndCQom,iv:DpOBvSEEwvqpO5mVuly9D+K6NKZqakBD7pM6EDqCQ48=,tag:c/w/fFdTxDq3T/VvxjuHew==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:UMmfVsYeWIYeKw7R4K5D85g04FEjwJG1,iv:xN1Nam/7dVNrqhztxXeSqIUrLzprTWb1HEhrYPCqmwQ=,tag:tkrh/Vo3gQdgVnvqN0z9lA==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:IwobScLqHY8de5iIFfBnpigBe68Cm5AViL0=,iv:8Sd5aad/mxBP+6Vp4Epl4hZt4xKkY5IeDWk4bKtEYfQ=,tag:+kwWzFl+KeYt8G7RGHWFBQ==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:9ieljTq8VyFdDQ==,iv:H0oOmmDQRF4wIDLFWPI5t6Qx1j2OtVOPeGk+PqLpk3s=,tag:GgqO/wiKcOmM6xkdExPw0A==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:oyGtVMz+LSY=,iv:mvM4AkJrE/A9C0P+rGhd+wqHUXwP8+eSq6NQ1/2Zh+s=,tag:rZzaSi2gReOpgEy7SQf5Zg==,type:str]
          networks:
            - ENC[AES256_GCM,data:pSo2jKusb6Q1hg==,iv:F8AbFfNhAi4EoYca0mhOlR/eajAx6LBkeuD5BZD2fTQ=,tag:bbeI0L3rrsK+5/55Md7dOQ==,type:str]
            - ENC[AES256_GCM,data:8H1WWRHlvIYeHuQTXQ==,iv:49hIBf7rR0BOtz9bw3M+Ss5Q5YWNAY/jdwZv1uKDb/s=,tag:RiW+ZZaWTT1N8chFAda1BA==,type:str]
            - ENC[AES256_GCM,data:9Qd2J4Rz+cI480TXloc=,iv:zWsEUaGWu9ZE4i6bS9ia/QiuaaXdgXW2Zu1izgAdUB4=,tag:LcdVJrjHtce18k9/tFlgpw==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:BH/jcsKi8wL3vz5CxVBNaWEh9YsPdJ+3,iv:NU79CLaoXT/IM+dfYbCqrQ4af5/ge+B08jEKHLvj5Es=,tag:d2j4pIe/u/ubIzpWhisBZQ==,type:str]
          policy: ENC[AES256_GCM,data:Qiwv5JXn,iv:Kfa79ZikCoOjYw8udOSiGBTbtWdOfD92f0pqeGuJJck=,tag:UyFObOPLSgULfSjq1fVgtA==,type:str]
session:
    name: ENC[AES256_GCM,data:7z3F776s9Fvi158PnRANdQ==,iv:qX1hxTFKVg0Pedq/w4PKLq/iUxd+r4M4qAWhWbR+MZ0=,tag:KDNT08HR7O1uXz5HAoMubQ==,type:str]
    secret: ENC[AES256_GCM,data:EW2Rky4fnd1PwItHGmshrjo/X+BODSkYJZx+n4fEuy7Pz9R00xKUKBmfjx2ADis=,iv:p9F+8vxrj14N6Tw7W5xkNX3coszALmU6qO6EjXytV0E=,tag:WeWn8U6u2qf925qSPXFvRA==,type:str]
    expiration: ENC[AES256_GCM,data:qZ6gAA==,iv:vuNBnn5WX0wR5qFAjSCgD8RQPuAe9PUUE1jfBPbxLEo=,tag:2WcuYty9mUVliDCg4XA+3w==,type:int]
    inactivity: ENC[AES256_GCM,data:SwEH,iv:rwHO+sXZuXoUUk0hNFvz6fvUfzjxz7BA+pqM8I8//bA=,tag:HUFGTl5Px2z0kNWi/kUyiw==,type:int]
    domain: ENC[AES256_GCM,data:jc3kvYc6wRVHWMEf25PXTh3BvVQJXQ==,iv:49Ks0pOhIbEQi7E2T00nXdi7G2UJbyIt/OmGCdiBO8A=,tag:fmSkUHJuqBBG84VtYKEMbg==,type:str]
    same_site: ENC[AES256_GCM,data:4RWP,iv:Z9SUuaFibqBy+1gtCTY/u2EkaCeKJGoGmx6nOE/i518=,tag:FFEzT2dhU6xPaEA6LPzxsA==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:9XIq,iv:NT/NZyXMOLDAaVbyw8z1d9FeBdjins4JDn50YaKnVNI=,tag:UzVT/9TExLTpw39ue+LtGQ==,type:int]
    find_time: ENC[AES256_GCM,data:xHf7,iv:lb3VCxApzvBxro5sm66VWmYI1iLx+74eOA/vSd/0Hm8=,tag:qhhxVczXtfTYSMA4vAIbLg==,type:int]
    ban_time: ENC[AES256_GCM,data:uzQl,iv:nZ7EU1OKLQ0zhZZn7JV7kDlq/KxJG62PoXrKywVWsoM=,tag:99fteAKaKMfvcqBt37WKIA==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:bf5NY4eOu7DGAyLbXJUGmJR1AVICwSwWmRiJffR1Czvnzdkz,iv:AdbQUI9ekaR0SzYq7FpSjjS3LzzxJB6IdbdR5W6m5Ac=,tag:5sbceQ6YT8uVvlaa/5z6/A==,type:str]
        issuer_private_key_file: ENC[AES256_GCM,data:+5iNgkM8OC9UkdOnhQdJEA==,iv:HJuMY1WSqCs2sdVjQuZnktw/N6sk20xvInJISsQVexY=,tag:wSh7fImAp+TKiLV4qVrfmA==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:XRcSlpfjtcRXRNDz,iv:OMEBPOc2R9yijYiyXC55F+a00oSRQWPGpigzPHd9+IY=,tag:pT3b6/0dr4xEtZfLfGP7pA==,type:str]
              description: ENC[AES256_GCM,data:5Og0fypuwjdLfL+N,iv:7vaWEbkbS5y5dcCiFdF7sXYF6khThuvSXjLoID0Wtpc=,tag:keX5dCTnyKBLz/TEDT3MLw==,type:str]
              secret: ENC[AES256_GCM,data:KIJaPRVjt/oTGuPZdIkZoXIBXoDurACXVQh0427xnKYK0219lDx3eSJe80aan4sCsGisOLAMJcKjJ96T9IjlJmGM//MMKU/BSmFRHwWKtNCJia4oCNjHFYcEHa8yZ/KSPPmgUfDBbvjPRr4U5R8Hv74ZWSDDaGtGPZAME68+IU/SIv8=,iv:kPd4AsurWgB3hHH7vYnBCVyv+bL8fnXAZ3jBGAIc6Zg=,tag:fpC0dTjpXgQ5UKJku6oq9g==,type:str]
              public: ENC[AES256_GCM,data:THK+L5A=,iv:ARN4D1htSMWhyChYdsFT/6AX7c9f2/h7WLMZ7sqXRfk=,tag:jGWIsyvey4qRmE1efMszEA==,type:bool]
              consent_mode: ENC[AES256_GCM,data:4sMpRKKLx3o=,iv:n2UnDnFkj2T2uF13sAbEsN7ja0Yy7Nl8yx247y+vogE=,tag:2AxmesGOEeBGbX+lWi+9sQ==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:ak5wyLy+RIaMjoFt40hEjqhiJb0FvkBg3XvssZzBFPpHw6aaIkmsvg16VkXEiQ==,iv:i0aSiD7xkzOydjbRB8W49MHjAUJeq2UNSNJp85EUog0=,tag:k1CRcNrSvNe1w9ET2QKoeA==,type:str]
                - ENC[AES256_GCM,data:8U5wP/eE5zPbSwie0jOwfvictOJpmooMBLYAmVGjDhi9m9yYPUJNVNTzImJyiZkiLafrmZAviOE=,iv:0CBUwGo4i6sJMMCSI41Y+b5T+jnh1LfUXpBHpvzmZV4=,tag:2UN18SlwJ3IAEsC6szRsZg==,type:str]
              scopes:
                - ENC[AES256_GCM,data:RnZ+ytT+,iv:kGi8VgsPiNJsIOG1kNX8xg1yinYBLbi/lm0qvnA5zLs=,tag:KGVtYF0CA5SAeJM7ya/KQw==,type:str]
                - ENC[AES256_GCM,data:Y5tYLmdAHg==,iv:8tE8Bt9caIxzs85QO5ICPAC7LDlRYzhsEUlYFewZxd0=,tag:s0af4P4R9GMdfK3G2dgAVQ==,type:str]
                - ENC[AES256_GCM,data:Y7yVXaSC,iv:N/5puh55CKiW0ct0SDO/mFDUg2g/dmwBQYeoohcULfQ=,tag:hnTg9BUBz1EbhAiUD5VMvg==,type:str]
                - ENC[AES256_GCM,data:Zn4JZIo=,iv:DvCuiG0jU7pXiJTLlyPzMioVJM60jlGlxyyTthPtcdY=,tag:ENEnDNpe8pxMT1QkRO1nQw==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:DBXAZg==,iv:QMAwyHz3JJEAvyimw54556OLFAZceP6FIc2QXSVUqCg=,tag:1HiO98i/464fYPjAgOSJDQ==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWWFsdkxQdzR6QXgrZkY3
            dm1XaU5tYWxKakEyU2V2czJVckF4c2lZSDJZCkNxNFM0UHpMY2cxL2tuUXBLd1Rs
            V29DWWhkZG9yeGFxZUY1VTlWTUJYY2cKLS0tIDA0dmV3Z0lzZ3NWL0JoSS9RMWJx
            Z3N6WEdEWFJnR2h6R3Z2dzZaMVRtbm8KIUXYxSFg41mSXo9VXysVAtR4q4vS/GK2
            lacWFg3lxeNmZx7JSAgXSayOd+Za9O0rYqlZcqm/ZtzQ1251iXwFAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T10:48:03Z"
    mac: ENC[AES256_GCM,data:3VacMtA24WsqCGyAK+ZsMRCeMViZ5nz+O8LzPu6ByIcVcNcp5jkowcMPjotwh4LYC7CHaScGCVXunxBRJbDg8fRb+5mUywpCojHeFaVXUByRVVe/0mL3q1PFF1GkXUoc0KMniIzZnWMsonQgFQeTv42ZReYsxYx4G8hUET/jdHI=,iv:VTP9xd7wQ1CxrMARgrIM+TlwRH+IYk6IaC/PiKDA+Mc=,tag:uzYmo22DEToI8AdULdPcMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
