server:
    host: ENC[AES256_GCM,data:uzxtIazJdA==,iv:ZiNAgoor26S7iiAN926hA+WbA6ydXZuTLTKiZxbMfCU=,tag:Kt9BHMfJ7GKSnjh4X3C/8w==,type:str]
    port: ENC[AES256_GCM,data:6pezow==,iv:rQJ1YajW2Jm6aq6tsP/f4gORAk9ZwAB6rwu55ncWtg8=,tag:aKdkzTaU5AdtoUDLdfy+6g==,type:int]
default_redirection_url: ENC[AES256_GCM,data:rk8RBvjOq0t8PAN7awNCEQ25CmLNJNOh2B1cfKUr1g==,iv:/0XBfm4ExmD/8JKGOGViEbspPQ1VwenI2+gMU7fqEbY=,tag:7J8r8N689I1ewa/ddtdxtg==,type:str]
log:
    level: ENC[AES256_GCM,data:ShFwag==,iv:OWXWKkqLdcGe7QmUkHtdZ12c4t+/hRx9vl3z+yFDRpA=,tag:8BqJhyEIHbK9L2TU8ag9Bw==,type:str]
jwt_secret: ENC[AES256_GCM,data:RY7MtP8P2NlOzvx8XZjmD43NduJNB4r9R92AMJHOVym0IzsrPU547wY=,iv:0b59kSamKkKMdvz5zj4psA9x8xSXiGZAd1+Ke2degVQ=,tag:UyYxD3kJzvErZToUFYmXyg==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:vcGAtmEW+9kwgwf8e90YG+DXzSI8c9vCfbUOzQ==,iv:W3rGpYAaMOY+vbUsFALj47Qyk7KVnekzwLIjyykYlIs=,tag:uJsliMongsJaXetR7vvK8g==,type:str]
    local:
        path: ENC[AES256_GCM,data:h4Z1tbU5SOws3V8WyNRPkyXs,iv:cksIlL/8bdibZ5sEMmMhXbMkcEOrOQLH8z8Tk6/VIZg=,tag:eRF+LGI86aWQ0rIXrw1JCA==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:uKO1s0uwPUpZg2RLjAnk0W8lUAOOJ4Sl,iv:jY0x++ZFPWvZOtdt66co7rJ+mqY+Y3DaaAHsVOuKyUM=,tag:5cID8BsU+7x8KDgMEXqtEw==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:0Z8tqlTQ/m8joiJ5BLaLsc6b1NjDkW92XZU=,iv:ZO2Z8bdhumxbcz6IqBPDucwMR/9vS1TElU9pktwdhmA=,tag:lSMreQMbUMYLcyHmiifIMw==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:rYi8HO8mOHsl6g==,iv:4tZJ2ICF2MyYkpaTKD8tobCNupSte0LABH+6aK/N3w4=,tag:1kXK+map2oX3RUD1j7rkdA==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:45mAiWmQyWU=,iv:UYuT/tU3hAZYU+kqotF6VBHmC5hQuVtfdZiRhVTK5uM=,tag:7KzcujXpck31zTW+gwetjA==,type:str]
          networks:
            - ENC[AES256_GCM,data:R+f8AyRffPpURw==,iv:Nc5A6/ZmJOMLoKaULlYUih4aeuJu7acieiL5KFAkTQ0=,tag:Fm+c4eTb9Iu+FiYDWfloNQ==,type:str]
            - ENC[AES256_GCM,data:N0BQclY/e54fJqeHgg==,iv:ctdmYEL/WS/DvOdhASB+cWmpunnHkEm7iGsKegzK2BE=,tag:nMXvzj8UgMk74Q9SzBvqkw==,type:str]
            - ENC[AES256_GCM,data:w/TMVsiTeWGEpb+zCXQ=,iv:oW1QX734ocjG7d+Kp0JrCHWRwnNjkEiJFi9YTOfQf94=,tag:RbxZTcWyri7d7Ev4MpxtPQ==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:1v8ToAHfK+WzoI5JwdC3FoicJeSIU7vB,iv:AlVN32NyVUnwlZdWg2ZLdWoI8bBP9jOI7/eIwMI/JeI=,tag:YWWWNVVDrR71KhJoxraqhA==,type:str]
          policy: ENC[AES256_GCM,data:7N97qB3+,iv:w/9KSlfuQkdeq5KcAr6HZ0FizPeNQcJUy3J0XCDvBzk=,tag:hpjt7gpH0yi2xvKOZ5EJ3A==,type:str]
session:
    name: ENC[AES256_GCM,data:+ugx4Zm58B4pDl9vE2wcPw==,iv:sUwYZwdh9ccuJSYQk3H6d7j+hnaGRt1WcuRipob6vcQ=,tag:s6nvPXXFkstsaZ+vJtTIlA==,type:str]
    secret: ENC[AES256_GCM,data:YHtWPDagUKDsyEXSGXAgzdT5m59sVgnji5IEsq0UNa/salHPfqugJ6Nr21BtVX8=,iv:IiNx42/2DBQ+M8OPufunHZyg4pF4Sh7udvGWrBTWOyU=,tag:/R89AEvhLd0/x7VqhHMFrw==,type:str]
    expiration: ENC[AES256_GCM,data:+DsgOQ==,iv:CW7vpytWuvLJbJtne2dav5scy+2GcqN72k7A2ddMWiY=,tag:N1K6McIFjDcJGgd12Yk+NA==,type:int]
    inactivity: ENC[AES256_GCM,data:UMzx,iv:H9p8lH/Tz+AbWez5Bu7IWsSVh0ACc/t0OEO88FKdWlM=,tag:B0YMOT3bAAfGtpHetX8HIw==,type:int]
    domain: ENC[AES256_GCM,data:qG82IW1cLEFZ/AI7v4QMrqhzSf4p7w==,iv:RP57hqkvD8bSD0jkej/qSkegkG7U8IZHc9Oxp5HMfF4=,tag:PBlAwRO8Wlml/cZMmiEErg==,type:str]
    same_site: ENC[AES256_GCM,data:BiCi,iv:c5tJS7A2Go2VwqMlm9+HtIzeZEfQCqxiUEy63t2kHo0=,tag:tFo+BRWOLdUJb+Yyn/hJVw==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:Zvoc,iv:NzvLyVGEtC0yC6sEEn2CDxuLaTyduuMonBPoHp2WaW4=,tag:kb2c3ilOhUNnDTOOust09g==,type:int]
    find_time: ENC[AES256_GCM,data:w4bP,iv:r3VRwyb3O2NJIE/1E5fkEy9jskhsdGDjJujVcjl6MMQ=,tag:MQNvntxvpCe7qPdzLRH5+w==,type:int]
    ban_time: ENC[AES256_GCM,data:4m97,iv:W+CUdj3FazieiiCBayjiJT6iTBLF52TPwNTFihsZptQ=,tag:atH9R5fADhdjhKP3tYkGCg==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:vHLaFNIYoTDVwmxst76w+Ak4gZoERFbtBfHI48SL0x+SUh8l,iv:5OKOXPBWfX2Adb6Hz6FMiEEnIzi8V4mMi91FYxN7jnI=,tag:eOlEi++fpOR1Qj8Qc3HD8w==,type:str]
        issuer_private_key_file: ENC[AES256_GCM,data:swHJt6dyIGJANp5mFN5ncA==,iv:oqSaE/jFsAnczDha4uI5PxEf0kW2X9UmyVTrzCjzuEc=,tag:RoYGQwUQjWgiJy0/k1SjbQ==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:htEFTs+sfV8JiFzq,iv:FQsddf38+9mHd+X4ejx27WNSJhGQF+JP/8b/jwXQUAo=,tag:8pVx+y3eE/BcqAV3pbiWfg==,type:str]
              description: ENC[AES256_GCM,data:zoa/tVFnmezICU0R,iv:/oI1RIL0hOaHcUTbSi6+PZjifK4UWrryA3BWyJaJon8=,tag:etosLimawYOqw6P+XDNYIA==,type:str]
              secret: ENC[AES256_GCM,data:1yhlCi3yLKWIkm3qi7dNJDWOd7Nl4aGUwgmrQtO+/AIFcMiLu8vk/ICkDKQyHSdfVmPdywIDaiXzP8PveFVzV2P7VzRpwRj8w2uU8rlgUaqfUrurAIZS67XaGe2QuTkhOpvZIp3rkeoZAtgVnUD+y4B20P96GramHqhmtO8GqJDGEic=,iv:BaysG3qXkuZ+i8qHFj5oPD6tWtCubCwz0H9euECQ8qU=,tag:afKhBYYndkegpm6gY0DW4Q==,type:str]
              public: ENC[AES256_GCM,data:c43sSWw=,iv:c1awsdosUt/AwJnzbEqzZ5sRzPVQMJarxDCdW0z1SlE=,tag:ttXq9B55qhn5DrkZEIVU5A==,type:bool]
              consent_mode: ENC[AES256_GCM,data:okpLaD2kOdI=,iv:T6baz27eMUnwt8BnWP4tH438WJPfkJYpM6qWciswCe8=,tag:rorrLLZ7/xzpOl15rqfxWA==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:rGkpja6DfwtZpwgLOLHQtfHCGhIdR+sfAojY9zNiIFNbUQMikNJAJY6ZwqYckQ==,iv:kaP7Wks5VTZw0ce9+CqyEjVzTcq82ZNHY9sw5OIAtU0=,tag:Nh7GK1ZkGgCFOHhKqDYAgg==,type:str]
                - ENC[AES256_GCM,data:tKmzfzLKry8nsn36Wy9VnlFtXHzhu1nhJircOjTGgzCFRchkVWVTNrZrL1XDfoNvOEzSd+iz/LU=,iv:dwtXm29lhQ7anbExokRJ//xip5MoMghovd9WHWb0AGU=,tag:L/8fTc4SskerYklvwlh5Ig==,type:str]
              scopes:
                - ENC[AES256_GCM,data:92iNI+GF,iv:yhmUgOhXDM8I40SRn2R1/HDz52by6Crl5flfdDh/u+Y=,tag:creL5ajv/TkbNhn4abugGA==,type:str]
                - ENC[AES256_GCM,data:NKpmzUMHmw==,iv:KFahhFxHzFAaqLAErrQXZgED7i+kI3YseUxolhyOEOI=,tag:qJpr98fEEMrxjSsTbUVEeg==,type:str]
                - ENC[AES256_GCM,data:qReEppRB,iv:7PIpu5S6UPrVTJlVrVZM+IgiMmf3CGrZA6OG5JkeBew=,tag:h89khdJAlBmz/wXQw/zwlw==,type:str]
                - ENC[AES256_GCM,data:/a7EmVo=,iv:WoYRvnjuNNMdcI1M4yR1Xs4+iE5w0Vzu4JjhdfaX94Y=,tag:Lf+0pGLfKXpKr8sBfcAf0Q==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:ojSJ5g==,iv:jiwacb/68mYUACd4P3DR7aRQ4YPUPh4vbR/LNZg6jC0=,tag:RzUFr34k/p4CBgcoxZQn8w==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdHcwQ2VXV2ROS1BnYVl3
            OVQwYmVJbStOVW44Z0E2WTFIc1E1bTVLWHowCm82TENNSlN6enhSZFBLZUw3QjRV
            STlWOGQxczFQdkM2SnVIaXdOSEEwenMKLS0tIDNrOWNSbHhvdkxOam94Qm15dHlJ
            N2l2NXlvTXRSM3dqVUlhbWJONUpQQUUKWEx08E/iOyV/o2+zsv+vJ7u4dLu4fM90
            IY7TDMnAmtRz85HnhE6ccKqJFmgVM70frmex6hc63SweZrgat6xV/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T13:50:52Z"
    mac: ENC[AES256_GCM,data:vcvZbqbWRUWpNqbcZpmnu1lSc3wsgPqegYJzY69S5NUicmK8tPbMG97TRldil4AYf4+/3TKF9QSd9vctvaWo1pxKgdgyp39GCOHJs7vQANb7xv84In4TPm9jhx69hjp60/AIeZAX0OnSc1F+HCCl/caWp/JCUwalZkoVFbhOPPw=,iv:TLw1oNQPvcaXwhNVfs1iVl4o/WPA3HU4lO62Mr3u4VA=,tag:y6S6s1rQJej2Ru0Ab9fecA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
