server:
    host: ENC[AES256_GCM,data:8TPCEjEMGA==,iv:2riXvhBjN7fTifBsSqXZ7a+97ETmieATWctS8nGfFio=,tag:QJj8GxFzcGjCRayB+ZKfyA==,type:str]
    port: ENC[AES256_GCM,data:LuYkxA==,iv:v1kWRdHSprU2fDpvuEW+n+zFODgXZBsweu/9IzdCLsQ=,tag:gAIyMBXHgRCJld2KFSkt7A==,type:int]
default_redirection_url: ENC[AES256_GCM,data:0KEYthMFEgUy4/oqVIPe14oaCel+l6ot8MBEjW/VYg==,iv:kEUN+XVV+UkN5pZbZV04EOGsyoTJ0hHj59zwb0drVFU=,tag:HJqhzqKZWgy6UzjPPUODuQ==,type:str]
log:
    level: ENC[AES256_GCM,data:XeuwEg==,iv:VYDaEQn4OiZ1NvyUaK1AqFsdGY/5UFt/g2w0jYj7c+k=,tag:8s+gRi6t2b5EGTHotPgwUQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:HxEoiwl5JMi+eSSnywxl7c67S8u/yFrwrCiWrebbIS71B9gtGBJrkrY=,iv:oyjKGXV0UrQDYKBfWxUyO8k1JerLTDjgIse0g42BCak=,tag:/591z5KfFucoCuizAFsJaw==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:LGhYTioolAr6Dht+K+GakxeTtBkqbvdpY/hT8A==,iv:h3TfK3qqoNY3FveprOgoW34dH1Wq1oLZ5QO22YlKQ0g=,tag:2Mi6XqXUwDWHdqGTUqba2A==,type:str]
    local:
        path: ENC[AES256_GCM,data:OTMxDAit6W7SMBUonx9kAKHN,iv:vMctIwjgd8NoJmLpKat/zN2OvkpSaH2wmEeQqwY1Oas=,tag:0YyDmbFk+cmu3TBNTaZtlw==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:s9PKpGmnzAWp48OW7PbzyvNet98Q/dFm,iv:CJgalavOg+9Qt8TisdZQg8e/fOf4aReY4oKIEkY74/A=,tag:sHQovPDhlE7TwvFnpoHSUQ==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:hY35NH2W82r4qXeF1AvmCqnx7fXEDpv24go=,iv:Kg4pUS8Fp9et4OD2JDRKj5NSF+EsG5L8P/nEoDRYFH0=,tag:Pv6KLo7GrzzdupYDmL1lBw==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:KfjwUwrSUY9x0A==,iv:RiSJrF4fPBBiMOvjdl85J27UprduYDDNlHAeb9chmtQ=,tag:CSNNVxqD5HOqZzRY4Hfi5g==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:xgpmTvci8Sg=,iv:Ws4j3YMNDvEsIoyeozhcUCBODVOzBrDQ8mutMQAaq+8=,tag:R/1PyuxXeqqw89p2Yal+3A==,type:str]
          networks:
            - ENC[AES256_GCM,data:Z9xD3lDYeLLWrQ==,iv:wlRngEXdjvWMMuIdzbpGAfaC7uKtOAaVip3SPFvzhJU=,tag:/30HMEdiDW1UPqYKNxSyJQ==,type:str]
            - ENC[AES256_GCM,data:+s7F1Ct0C4jhs7RWeQ==,iv:HIaLZE3tDjNfQIVc88RvI+ANFfrvhsIEM7ojFNLT3JY=,tag:wETV/P5EdlVkUlLyfuMLhQ==,type:str]
            - ENC[AES256_GCM,data:8bjbY2ab/Z2RGmsIGoo=,iv:hf82i6jYGrkseVm5Q9OzAkyzDfGBfmJU7MtM3AHpkTs=,tag:vjmu0aw6FwlAOcvwPPtj6w==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:0+30H1yWqLMKznjspu18/pFIdkVd7rAq,iv:7m8m3UWRLmfynH18qIQPl+1IlVuifmLuktvUxixbKSY=,tag:KfR7D2O4xT+ovpPlOEFjWQ==,type:str]
          policy: ENC[AES256_GCM,data:JP3y84Ik,iv:Ywa6liVXXqt7sqekXoRdqwVCLCxef/JGroILhcuRvKA=,tag:yIDQjKj9FCsIiOf89PAWKg==,type:str]
session:
    name: ENC[AES256_GCM,data:XLW7mJi/Ac00TultJ/1nMQ==,iv:3eV4+ur/LIbDFfbHwaT3YRf4Js8a8/rWD2zN0fYUfOo=,tag:Zi4DDncDwNrzpavAj0Q5eQ==,type:str]
    secret: ENC[AES256_GCM,data:AXAKl9J6l+uerpJN2/ZACMv/aRIDKngPHnRlNDg18gInBwZAu74mYxlUhEAuj2U=,iv:UHayCbqzli+zD+I70AtZJXW741D/Et5DF2GLGdC8Gqo=,tag:dM467o05t9f9VSLXP9L8Qg==,type:str]
    expiration: ENC[AES256_GCM,data:h/oRKA==,iv:Bz+I8PuJTbdpf9pvGQTb2jGYf6ItSQku17zbsaOdVaQ=,tag:XNYZhkR+V3R6ED6hGm3B2Q==,type:int]
    inactivity: ENC[AES256_GCM,data:3WAo,iv:rwaLjOlw0NWn+t1CrVIMNNpzAIqtNVyvudqQ5aS1hf8=,tag:hdF0pysFDA1itrQ6dZmsIQ==,type:int]
    domain: ENC[AES256_GCM,data:awrEHmr/jOMcu5YxSC5m9pPIerzzzg==,iv:emW8qmn35v+lXXIFDSX2epbFUrSERwxytEzyiI4TPnw=,tag:dzT/w3AQbaL/duWQIn42Rg==,type:str]
    same_site: ENC[AES256_GCM,data:zcwx,iv:JwolXhvyVUY/DLQZ4e9o9w0ycv1oh/e836dSG/Z/W0I=,tag:ldzqwpTJ1sun/TnphjmhIg==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:vQNF,iv:SSRjZMdhXBW9s9/oSMtqEUzBuex7xdy+0/HsHsOCraQ=,tag:8N0AO0xK/IkBT0ni3BEzCg==,type:int]
    find_time: ENC[AES256_GCM,data:YBJ3,iv:lodAsTbG6bv3xzg91Ar8bBAALPvgT1rV+bgVVsEn4ps=,tag:kBSYAGU3Zc80CvZSUX2LXQ==,type:int]
    ban_time: ENC[AES256_GCM,data:0+WP,iv:WiALof4qullndRarlhtyIuwksHg7pCHB/wZIl6dm9Xs=,tag:mjbkFZGxHMj0O8FH+j94GQ==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:aHKpySa0rYhdW4kYPfQ4XQEBKXfepbROguYmEhGd3i97nKPA,iv:4CTQ+dZXpC+GfjZhlaUEwb7CL5U1MKxFZAcbAMXZF1Y=,tag:wWV0cZzU3ki3i+my+75zuA==,type:str]
        issuer_private_key_file: ENC[AES256_GCM,data:1mT0bHvFayDYGoLyBtiFtA==,iv:fb4ppwUuLbX9y5F1NNM2debXDLGDNtCICa5rVlCtCXQ=,tag:NRDAPxZ8XQ8uOFn95rE+QA==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:vQ9djr+OXvxjEZCh,iv:tLH4/Jj4o2p9MUyahIlgaq06WnnyK33InlbByb1jgv8=,tag:ilX3gSQRmI2K724kpYLauQ==,type:str]
              description: ENC[AES256_GCM,data:5jIP1gAhQpQSW15U,iv:YAD7YvSi38wLiC/gUgLoLcr9vXX8lN5R/F3I3HItHg4=,tag:Wr2HI3uIw1CvNu24EF1vtg==,type:str]
              secret: ENC[AES256_GCM,data:o6aYmQBteDSck/yoL9DM7QMohTeymnJouvI6YW4Ae5ku5Q4inkQqiZYJW7tz5Cd6wDsHvwoNxSP5F7Oo1vnAr6ewdrqRpo0VuXOiy/Qh4r7PPtP+8du9sPXWxJbouHmDb9C7npwTL9g10x+khr3uRGIMoUK1lsRUqlTH1NPwBT/7fNc=,iv:ep4W8cYp+mnq0hw8Vif87S6ku6QmiPD/NeE1hbcUUnw=,tag:1B4T8cMr9VigsV8hcx4m5g==,type:str]
              public: ENC[AES256_GCM,data:6nGbrm0=,iv:GH8CNrPlmuI+qIjUaXYAh28JwngtYVtXVBam22sx5w4=,tag:avgI5E6ZX9mlDqvQDS0e+w==,type:bool]
              consent_mode: ENC[AES256_GCM,data:Vye4lGaCLf0=,iv:lZQAWu2uqEk9U75qPEzxb1XX1uEmvBDT7zKWW/AC7G8=,tag:4eUBL28znJc2vy1Q3gqLCw==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:Q6LuCwjNju82v5lG1WDfWH8mJwsLTIoV9HiBga9dF1XZP21dUB8nM4SQkfqkag==,iv:FfPoLagWN3DEkVHWk8iA3Og+548KNPmKMTRp/25eRxA=,tag:e/Befb7BRm3MbiEjXaOB0Q==,type:str]
                - ENC[AES256_GCM,data:C4xe7l8etOMyn20xJa3QS1SdwBkOVPPsBK4W55ckYbeSytwWUt1n1YUxfe/etRi2yM3lYRXSqRc=,iv:Lzr3SOKHDxFk19pk5slDLCBDOQkF/IXlynTBwxiOsEA=,tag:hB2jim2Xhpmk+4A1AGWlsA==,type:str]
              scopes:
                - ENC[AES256_GCM,data:48C6Pbj/,iv:iXG9ObbZ/LfKgoFScWmuGvjTzmKKkaLmvMgEN8CFfsA=,tag:AlVx0TVKoqoYr53ISR0dZA==,type:str]
                - ENC[AES256_GCM,data:+2MF9mzxow==,iv:69HyAXsNuF4anNHSNaya0KdQRiLjj1a/fi8YSu9P7uI=,tag:FIGMvp+2jkEroGWjLI0TGQ==,type:str]
                - ENC[AES256_GCM,data:6gT5qBAn,iv:+PszgFVoJ0CUxW6XREKuWsmpGfL8JvBlI4JkSsubAW4=,tag:fLk3dld9lk/Ej7JLmQxJ4Q==,type:str]
                - ENC[AES256_GCM,data:ApSiwck=,iv:sCncia1Gdryi32gRLyt/6ngCqz0yKp8A7eENLN3qrOE=,tag:JnGbGeXrS3typ0cm+swSug==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:c/UA6w==,iv:fdBJQ1kzV23d6uQ5niroKOR/RZhHFnPZpi4IBQHUJzI=,tag:sOb1krpW008/hgoLFoIdqw==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ1NaTXRFYTdGVGxYeFc1
            OUMzR2FrYXNKdGlxbzViN0dXV3F0RDlLTTJvCllXKzB3Wlg4WEN4THRTRFp4cGdq
            U20zQ013NlV6L3hkQmVockZzVFpXd3MKLS0tIEQ0TmVIeXdSOXJNcUR2UFYweUxG
            Q0E4WVMycEtlbTRlVy9Tc0NQaUtNVWsKXRCTP/8bv36+xboGRBkIgPALtjvcha7e
            m/IFRsM5aWCTLj8abhnruTWs4G05RIIWWrsYC7zBoRqpiLGuoj/DVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T14:55:14Z"
    mac: ENC[AES256_GCM,data:CiSp+8TfesW2j6r+h0B+XCuUD7wel/4eP+Fi9XZygr8YnXClwcnxECffsBhNC9yH83/IJNcfPbvQjMh3gQfVZSHpDeoTHZzuP1IF8f1vjtqii525q9uNvuw969Nk8ZLFSZo7GNEZ87c7eT2EFTagT+tgNTP04lDAJyVU+zOSQqc=,iv:5uy8PxmskMMz/FQzCu8hh5PYsPkTzn/yd3KRl8WbfHI=,tag:wa+n70yWMcuS7biRKBF5yg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
