users:
    admin:
        displayname: ENC[AES256_GCM,data:HHgeM3ovkxThog==,iv:1k0g7tnbwzWtZqKu4Tc6z2eP6m6tzi9XtATBRjHsGkU=,tag:NM1tWcrxJ6KQfRjzcrAL0A==,type:str]
        #ENC[AES256_GCM,data:t7EQdh52jiEK,iv:X0S9Dws2fNzChUksD+9OtIMjD0d20AzEIbGVRPR/L74=,tag:ws1YAWnF69J0cxU8/XMmDQ==,type:comment]
        password: ENC[AES256_GCM,data:IEZfBfwXnofNparltUtsbU7IlBCOP4PQxR8M7R5SZWqzCocHwo2A1SI6TaSN4oF3ocy/tOH3pB9Gi8dRc8LkVg8QtgO4BwaCToyXFmXNrnHQBF2jCAfGt63KEqgkIT47pQ==,iv:6lnaGqIbJIJU8uszbVEe4qqvUx7WLcrKatEEfq5gV2Q=,tag:+MkcdhxHuL7O7YqXMjsGbw==,type:str]
        email: ENC[AES256_GCM,data:Wg6EbK4atrumMKJdJWiTGvY=,iv:WP3c79373ohKBS6P3QHaV3nVKcCo17odmnBsqMAJnB4=,tag:t4K4Kjoez/23gNjY9MoLuA==,type:str]
        groups:
            - ENC[AES256_GCM,data:a2Z5zXIZ,iv:qKZ7chiwOIqMo3A6UX/Cbu4NW7Y+7/AlBeOiWOJcDKg=,tag:XnZJaIgTPrCTff5mzd/V9g==,type:str]
            - ENC[AES256_GCM,data:Y00O,iv:1wlRn0cAJy7v6kyAdQi+t7np/FY/GYNFKmDJzQUR16g=,tag:WbaDDFwdocInB+PQJOqsyQ==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SlVyeTMwSlRvakNlM3FU
            ZjFCaXNCbUpVUE04TWVYckZnUnlKMExIQVJRCm5ZdlM1bG9jYTBBTUErdCtNc1NF
            UmlQdVVycGpjK05yakcxM3J5YWxOaHcKLS0tIDczOE5ZS3cwcld5bDdkQTZRMFB5
            QWNrZGpDYjJUZHNDb2t2NnNMaEpVSncK/f1+LTFmbnrz7b1MHRYka/wyPOEochq/
            quQe3XevXDdk0DhE8ro1xPaVMU85UVUlZsNwVbDBEAtX0Y4blnwhQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T14:55:14Z"
    mac: ENC[AES256_GCM,data:4ir3M76kDo+a+mzS1tVx9HDdvldFr3IEojzkDepJ2ZV4ll1QCl8Cu1b1iRscIy94OdLLAOwTE5QFbdmt/qONNhSKCnG+Wr6Vt87d3tEz8C2HjJcOjBd3Vcy/W4uya8rBwVSYz9xMgx/Tri9BsOTCBTpEaiRBasZdwqkyEYQeJv0=,iv:jdCnGSvwpu6lfHqORwEZNLwLW4bXa0SjLkre+RFve5Q=,tag:4hId7fVGlcOb5zaSkt1Wiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
