users:
    admin:
        displayname: ENC[AES256_GCM,data:pOI3x7XNUbTDYw==,iv:r1hXUyMWPGNM6Cw95SKHCADkpn+clCdwEbonUFoF4CQ=,tag:v2Cla72eTDE6Mp5b3McUQA==,type:str]
        #ENC[AES256_GCM,data:rrVlLNXFXT97,iv:pV7sfeRKaTDfX9kNuOHQiBWQ8b3wC0K97maZkh8iwb0=,tag:Z2XOHeJW6cezW0KVHgkmfQ==,type:comment]
        password: ENC[AES256_GCM,data:ZHf3Sj8GHZ2QLBQFp5XzqK3LyoD+I+v2lJGkfIW3y2mUDDzc2o+mMAgNZx+AkPw3Ud5kMkGL3FCgp5QclyZcnYxaKn5Nhj1Uz65LOhgKbZDmbzNwEAuUcnVOKzhbPHihyw==,iv:SzehpTZgUJDUdcabF4TMUdOOoFWlV+oUDyIHwxgSaRI=,tag:Ajj9LA9280TKuSkv2cb+jg==,type:str]
        email: ENC[AES256_GCM,data:ix1klZFFKJJ5U5r1cBz3o90=,iv:v/ACEvjkpPNGaQ4Hv8xdO6yE7T1bY3CeB1JlyvMsRc4=,tag:zQxlP6zXoa1ra+1WHh0KjA==,type:str]
        groups:
            - ENC[AES256_GCM,data:+iDGPgxD,iv:8kvGHEsmOq7+5aekZfWf31PKHk0epEf3PnkwjddHX2Q=,tag:ybVj8LHSWiFArvJpf1vJJQ==,type:str]
            - ENC[AES256_GCM,data:6VMO,iv:8yycFHAr6GyAq+EVbMH9hBZbSxyyKqlhTtQzkeysy28=,tag:WxrXRiHmjlvVMcTOHiiZng==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRGpHRmM3dlI5QStOaTRj
            dlM1Z3BkUjB0VS9Ta01BSStQTkUzUjFnRWhJCmNpYk5LdWZ3M0M0ckdVeEplWHkz
            VHEvWVhvRjREUjR0Uk1RcjFNRFFFU3MKLS0tIHBpRnVxNzh1WmJUdUxkUUNRVEtq
            c0NIRHlKbStrSXNUTHJiV0tJYXdVcm8KsEcskpvQKzrNCH6ECGJxFMiLoRMW7kte
            pQfyCv/BHdx4uKG1R1GpItXVFQziCkDvk/TI4Hu3ePiUTVC6jbYOKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T10:48:03Z"
    mac: ENC[AES256_GCM,data:exLmq4IZGPUdodEJXzPPP0dIqtdVbY4pbRtOYAYyJMIGSmLWEFAYRLmQ17w4Ze2fpszLICJ0u3zKmYxVrcuqh7GnY3xesh/iSiwkOpNvearqmtnhRjt5S7OVwtGkeXmhMfjv42n1tr7l3MnkDqTSjxwFgg2ihWqm0udLvPf5lZ0=,iv:/N7fmwf+6B4OND1Rz1H5IAHhHprjZqTtUNvg5ZGlKwM=,tag:tRm1gfAcSX0CEdgkO8Dr0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
