users:
    admin:
        displayname: ENC[AES256_GCM,data:K905XUAMn9mb6w==,iv:vT4sRjGlHhzJEiZGBH6XsXfGjxkg8w+aBNvUX1xkFyA=,tag:xW1Tp/ZxdMj7O7UFbNUx1Q==,type:str]
        #ENC[AES256_GCM,data:7pWyI4aznus4,iv:OcKZ5OA78wrdsv5vaXhPduDxEHxLEGaG7yPdhLsFUME=,tag:g1F7vJJYWABrX6BHYsT7fg==,type:comment]
        password: ENC[AES256_GCM,data:yfAyUwKjqqfmr11nltpM+PXNzLbMMrU2eWm9b8fCZ6dwO6urWxL+Qisfyg0Ffa+WBTnUJUrrEd3n5tnJJDk2rHvB39hzqc/Ga3D+z3yTIbMAmN/boGgt1JiNeGy4krbypw==,iv:COdXf5q0A2FjJmmn+l0EfV473dn8W8RDZyKwWdnJpls=,tag:Cb5YqeDHZJlEqpP1NOhOiQ==,type:str]
        email: ENC[AES256_GCM,data:OD17ZRgNQGRL48ZQc5Hy9pg=,iv:287lQ9ILgkio2SU8OHtZZZxE8p6oYh61+ycpNYeTKx0=,tag:QHs3PTL6Sq9PfR9GXxCT9g==,type:str]
        groups:
            - ENC[AES256_GCM,data:lT88EOx6,iv:TpGy98tqUUdQrub3ge53YjThnt2iw6Wy8Fiwb7OnU9I=,tag:60XgXxuXzuX5GmlwldevIA==,type:str]
            - ENC[AES256_GCM,data:SNOU,iv:D19ITZSLjO+B8tF6wlnpVo2nXWJkS4mCY3FOttX/gUA=,tag:VS0vey/rSGr1uKyU/chICA==,type:str]
sops:
    age:
        - recipient: age1mxkhk7p4ngsl7yagkp0m2xa5ggzl2ppfgrfuadadsxdus8jcpugqsn9x5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUkoxclJONkxNVzcrdlZG
            K1lGYWJialVpZFdUdlBZRVViTVNTUFNUWGtzCnFKTmk5bGY1bjRML1M4OGxkRHlM
            TTN1UWY1V2pReCtsZzBuSW5RMFkvSk0KLS0tIGtQakJxemlzbzhLaFJONzZYOTla
            ODRjaFovZDVIb0lXT1Q3eXkyLzYrdjAKMLNctDk+CNV+P6nV+qre455AkHbfmEQ2
            zqADbznK652ThkE517FeOMyUWcHLCn3ZnAjAns/+dnoZaz9TV86Brw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T13:50:52Z"
    mac: ENC[AES256_GCM,data:bloKT+5nqBkQWV7RFFyIexlJ77xHtNtWKz38jX+1B+iVxEpP99NYwTuK1SSZfNUmUt41+P5Uk75Gcnb1tC/QgzBFCWfJRhkqNH1W+0pc71TYLlFBe57Gozm9JqpVGuRM8AGQOZHdYrvW4N4yuYqomzqRQPC836iwnQgS99obxIE=,iv:FHGrXFdlAuDaosJCu1GOTWF8HBTdYsXIWH8ambsR0qk=,tag:Lj2Vp34P4eK1XpWSLJIeDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
